pipeline {
    agent any

    environment {
        AWS_REGION = 'ap-south-1'
        PROJECT_DIR = "$WORKSPACE/flask-todo-app/"
        TERRAFORM_DIR = "$WORKSPACE/flask-todo-app/terraform-setup"
    }

    stages {

        stage("Checking the code") {
            steps {
                git branch: "main", url: "https://github.com/avadhani-sandeep/Python-projects"
            }
        }

        stage('Provisioning and Applying Terraform files') {
            steps {
                dir(TERRAFORM_DIR) {
                    withCredentials([
                        aws(credentialsId: 'aws-credentials',
                            accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                            secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')
                    ]) {
                        sh '''
                            terraform init
                            terraform apply -auto-approve
                        '''
                    }
                }
            }
        }

        stage("Getting the SNS-Topic-Arn") {
            steps {
                script {
                    dir(TERRAFORM_DIR) {
                        env.SNS_TOPIC_ARN = sh(
                            script: 'terraform output -raw sns_topic_arn',
                            returnStdout: true
                        ).trim()

                        echo "SNS-Topic-ARN: ${env.SNS_TOPIC_ARN}"   
                    }
                }
            }
        }

        stage("Building the Dockerfile") {
            steps {
                dir(PROJECT_DIR) {
                    sh 'docker build -t flask-todo-dynamo:v1 .'
                }
            }
        }

        stage("Running the Docker Image") {
            steps {
                withCredentials([
                    aws(credentialsId: 'aws-credentials',
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')
                ]) {
                    script {
                        sh """ 
                            docker run -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
                                       -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
                                       -e AWS_REGION=${AWS_REGION} \
                                       -e SNS_TOPIC_ARN=${env.SNS_TOPIC_ARN} \
                                       -p 5000:5000 \
                                       -d flask-todo-dynamo:v1
                        """
                    }
                }
            }
        }
    }
}
